version: "3.7"

services:
  app:
    image: jboss/keycloak:15.0.0
    volumes:
      - ./.docker/keycloak/data:/var/lib/keycloak/data
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - "8080:8080"
